version: "3"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:head-alpine
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    volumes:
      - ch_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
  
  qdrant-database:
    image: qdrant/qdrant:v1.3.2
    environment:
      - QDRANT__SERVICE__API_KEY=qdrant_pass
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  ch_data:
  qdrant_data:
