version: "3"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.10
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data2:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  ch_data2:
